model:
  source: git
  directoryName: intfloat/e5-small-v2  # repo name
  template:
    file: ""
    custom:
      triton_store_path: "/model-store/"
      use_cpu: True
      models:
        - name: "e5-small-v2"
          checkpoint_path: "/models/intfloat/e5-small-v2"
          triton_config:
            trt:
              name: "e5_small_trt"
              max_batch_size: 128
              num_instances: 1
              min_shapes: [1, 2]
              opt_shapes: [1, 20]
              max_shapes: [128, 128]
              max_queue_delay_microseconds: 10000
            pipeline:
              name: "e5_small_pipeline"
              num_instances: 1
              max_seq_length: 512
          input_type_prefix:
            query: "query: "
            passage: "passage: "
  path: https://huggingface.co/intfloat/e5-small-v2
  checkpoint: ""
  revision: "1"



resources:
  limits:
    ephemeral-storage: 30Gi
    memory: 8Gi
    nvidia.com/gpu: 0
    cpu: "4000m"
  requests:
    ephemeral-storage: 3Gi
    memory: 4Gi
    nvidia.com/gpu: 0
    cpu: "1000m"
